# Generated by Django 4.0.5 on 2023-05-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menus',
            name='descriptions',
        ),
    ]
